server.port=7000

spring.application.name=gateway

spring.cloud.gateway.server.webflux.routes[0].id=patient-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://patient-service:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/patients/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=2

logging.level.org.springframework.cloud.gateway=TRACE

management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=*