spring.application.name=billing-service

# The main web servlet port (for actuators or REST endpoints if you have them)
server.port=8081

# Configure the modern standalone Netty gRPC server port
spring.grpc.server.port=4001

# Enable gRPC Reflection (using the modern official property layout)
spring.grpc.server.reflection.enabled=true