spring:
  application:
    name: patient-service

  datasource:
    url: jdbc:postgresql://localhost:2000/patientdb
    driverClassName: org.postgresql.Driver
    username: patientuser
    password: PASS

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: all


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  sql:
    init:
      mode: always

